services:
  chat-main:
    image: nginx:latest
    container_name: chat-main
    depends_on:
      chat-ui:
        condition: service_started
      chat-api:
        condition: service_started
    ports:
      - "37006:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - chat

  chat-api:
    container_name: chat-api
    build:
      context: .
      dockerfile: ./Chat.Api/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - AppOptions__OpenAIApiKey=${OPEN_AI_API_KEY}
      - AppOptions__MaxPreviousConversations=${MAX_PREVIOUS_CONVERSATIONS}
      - AppOptions__UseMockChatHub=${USE_MOCK_CHAT_HUB}
      - AppOptions__ResponseDelay=${RESPONSE_DELAY}
    volumes:
      - ./SystemMessages:/app/SystemMessages
    networks:
      - chat

  chat-ui:
    container_name: chat-ui
    build:
      context: ./chat-ui
      dockerfile: Dockerfile
    networks:
      - chat

networks:
  chat: