apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
  namespace: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
        - name: chat-ui
          image: chat-ui:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-ui
  namespace: chat
spec:
  selector:
    app: chat-ui
  ports:
    - port: 3000
      targetPort: 3000
