name: Publish Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Chat.Api/**'
      - 'chat-ui/**'
      - '.github/workflows/publish-docker-image.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract Chat.Api image metadata
        id: chat_api_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.CHAT_API_DOCKER_REPOSITORY }}

      - name: Build and push Chat.Api image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Chat.Api/Dockerfile
          push: true
          tags: ${{ steps.chat_api_meta.outputs.tags }}
          labels: ${{ steps.chat_api_meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      - name: Extract chat-ui image metadata
        id: chat_ui_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.CHAT_UI_DOCKER_REPOSITORY }}

      - name: Build and push chat-ui image
        uses: docker/build-push-action@v5
        with:
          context: ./chat-ui
          file: ./chat-ui/Dockerfile
          push: true
          tags: ${{ steps.chat_ui_meta.outputs.tags }}
          labels: ${{ steps.chat_ui_meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
